### ISSUE TITLE
Cannot paste if file selected + "...0"

### ISSUE THREAD

**Issue by asiloisad** [Souleste/tree-view-clipboard#1]
Hi,
thank you for make this package, it is very usefull. however i have find one bug and one improvment.

1. if copy file/dir and try to paste it to tree-view, if dir is selected then its ok, but if file is selected then Unhandled Exception occur. "lib/tree-view-clipboard.js":115 should be change to `command += this.paths(true);` or somethink similar

2. if try to paste the file which name already exists, then file is overwritten without information. standard atom behaviour is additional post number instead of overwrite the file. please consider it.

best regards, sb

**Comment by Souleste** [comment]
Hi, @asiloisad. These issues have been fixed as of https://github.com/Souleste/tree-view-clipboard/commit/731c8d106fa790a2b5780ba4de8394fe1b412572. 

The paste-over-existing is handled the same way windows does it (suffix of " - Copy(n)") rather than a suffix of "n".
